# Advanced Ban
# Plugin by Delta203
# v1.3 BungeeCord

# Languages supported:
#   EN    | English
#   DE    | German
language: 'EN'

# MySQl connection
mysql:
  host: 'localhost'
  port: 3306
  database: 'test'
  user: 'root'
  password: ''

# Inform other team members about bans, mutes and reports
notify:
  mute: true
  ban: true
  report: true

# Command query fetch every x seconds
query: 10

# Max temp ban/mute value
max: 730

# Console
console: 'Console'

# Chat log
# Placeholders:
#   %player%    | Player name
#   %command%   | Command
chatlog:
  connect: '<b>%player% joined the game</b>'
  disconnect: '<b>%player% left the game</b>'
  command: '<i>%command%</i>'
  # Report reason has to be registered
  autoreport:
    enabled: true
    reason: 'Chat'
