# Advanced Ban
# Plugin by Delta203
# v1.3 BungeeCord

# Languages supported:
#   EN    | English
#   DE    | German
language: 'EN'

# MySQl connection
mysql:
  host: 'localhost'
  port: 3306
  database: 'test'
  user: 'root'
  password: ''

# Console name
console: 'Console'

# Max temp ban/mute value
max: 730

# Self interactions (Ban, Mute, Report)
# Debug purpose (Default: false)
self: false

# Command query fetch every x seconds
query: 10

# Chat log
# Placeholders:
#   %player%    | Player name
#   %command%   | Command
chatlog:
  connect: '<b>%player% joined the game</b>'
  disconnect: '<b>%player% left the game</b>'
  command: '<i>%command%</i>'
  # Report reason has to be registered
  autoreport:
    enabled: true
    reason: 'Chat'

# Advanced Ban panel
# Placeholders:
#   %uuid%    | Player uuid
#   %key%       | Login key
link: 'http://localhost/abpanel/?uuid=%uuid%&key=%key%'