name: AdvancedBan
version: 1.3
author: Delta203

main: de.ab.delta203.bungee.AdvancedBan

# Permissions:
# - ab.ban
# - ab.tempban
# - ab.unban
# - ab.mute
# - ab.tempmute
# - ab.unmute
# - ab.check
# - ab.panel
# - ab.cantbereported